[workspace]
default-members = ["bench", "pulldown-cmark", "pulldown-cmark-escape"]
members = ["bench", "pulldown-cmark", "pulldown-cmark-escape", "fuzz", "fuzzer"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"